### PR TITLE
Fix: Prevent render Multiupload in Collection Modal

### LINKED ISSUE #73: Add from model type not working anymore
If we have a link to a image and use the "Add New" button it will not work anymore.

Maybe adding a check if it's a ajax call for the select provider and ignore the multi upload in that case ?

### PR DESCRIPTION
**Pull request by silasjoisten**
In this case i override the Add new button for this block:

CleanShot 2022-05-15 at 10 42 25@2x

And i want the multi upload in this modal. So checking only for the `isXmlHttpRequest` is not the best option here. In Favor i check if in query the `pcode` isset.

Maybe there is a better way but i could not find one.

closes #73

### CODE REVIEW

**Comment by silasjoisten** [comment]
@mpoiriert maybe this will help to solve the issue you have created here: https://github.com/silasjoisten/sonata-multiupload-bundle/pull/74/files

File: src/Controller/MediaAdminController.php [hunk 1]
```diff
@@ -23,6 +23,15 @@ public function createAction(Request $request): Response
     {
         $this->admin->checkAccess('create');
 
+        if (null !== $request->query->get('pcode') &&  $request->isXmlHttpRequest()) {
```
Comment (silasjoisten) [inline src/Controller/MediaAdminController.php]: @mpoiriert if i am not wrong i guess checking also the pcode can be helpful to figure out if the modal was rendered by the collection type

**Comment by silasjoisten** [comment]
@OskarStark maybe you got an idea here? Am i missing something?

**Comment by silasjoisten** [comment]
released in 4.0.1
